version: '3.9'

networks:
  default:
    name: movie-network

services:
  mysql:
    container_name: movie-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-movie_db}
      MYSQL_USER: ${MYSQL_USER:-movie_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - ./docker/db-data/mysql:/var/lib/mysql
  php:
    container_name: movie-php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - mysql
  nginx:
    container_name: movie-nginx
    image: nginx:stable-alpine
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  portainer:
    container_name: movie-portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - '${PORTAINER_PORT:-9001}:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/portainer/data:/data